"""
周度简报生成 — 可执行脚本
用法: python weekly_report.py [--db abs_demo.db] [--output report.md]
"""

import sqlite3, argparse, json
from datetime import datetime, timedelta

def generate_weekly_report(db_path: str, output: str = None):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    today = datetime.now()
    week_ago = today - timedelta(days=7)

    # 1. 本周回收
    weekly = c.execute("""
        SELECT SUM(c.actual_amount) as total_actual,
               SUM(c.projected_amount) as total_projected,
               COUNT(DISTINCT c.product_id) as product_count
        FROM cashflows c JOIN products p ON c.product_id=p.id
        WHERE p.is_invested=1 AND c.is_paid=1
          AND c.start_date BETWEEN ? AND ?
    """, (week_ago.strftime('%Y-%m-%d'), today.strftime('%Y-%m-%d'))).fetchone()

    # 2. 按资产类型
    by_type = c.execute("""
        SELECT at.name, SUM(c.actual_amount) as total
        FROM cashflows c JOIN products p ON c.product_id=p.id
        JOIN asset_types at ON p.asset_type_id=at.id
        WHERE p.is_invested=1 AND c.is_paid=1
          AND c.start_date BETWEEN ? AND ?
        GROUP BY at.name
    """, (week_ago.strftime('%Y-%m-%d'), today.strftime('%Y-%m-%d'))).fetchall()

    # 3. 评级分布
    ratings = c.execute("""
        SELECT current_rating, COUNT(*) as cnt FROM products
        WHERE is_invested=1 GROUP BY current_rating
    """).fetchall()

    # 4. 下周到期
    due = c.execute("""
        SELECT p.code, p.name, s.next_check, s.stage
        FROM project_stages s JOIN products p ON s.product_id=p.id
        WHERE s.next_check BETWEEN ? AND ?
          AND s.stage != 'closed'
        ORDER BY s.next_check LIMIT 10
    """, (today.strftime('%Y-%m-%d'), (today + timedelta(days=7)).strftime('%Y-%m-%d'))).fetchall()

    # 生成报告
    report = f"""# ABS投后管理周报
**{week_ago.strftime('%Y-%m-%d')} ~ {today.strftime('%Y-%m-%d')}**

## 一、本周回收概览
- 实际回款: **{weekly['total_actual'] or 0:,.0f}万**
- 预计回款: **{weekly['total_projected'] or 0:,.0f}万**
- 涉及产品: **{weekly['product_count'] or 0}个**

## 二、按资产类型
"""
    for row in by_type:
        report += f"- {row['name']}: {row['total'] or 0:,.0f}万\n"

    report += f"\n## 三、评级分布\n"
    for row in ratings:
        report += f"- {row['current_rating']}: {row['cnt']}个\n"

    report += f"\n## 四、下周关注\n"
    if due:
        for d in due:
            report += f"- {d['code']}: {d['stage']} (下次检查: {d['next_check']})\n"
    else:
        report += "- 无\n"

    report += f"\n*Generated by NPL Weekly Report Generator on {today.strftime('%Y-%m-%d %H:%M')}*\n"

    path = output or f"weekly_report_{today.strftime('%Y%m%d')}.md"
    with open(path, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"  周报已生成: {path}")
    print(report)
    conn.close()
    return report

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="周度简报生成")
    parser.add_argument("--db", default="abs_demo.db", help="数据库路径")
    parser.add_argument("--output", help="输出文件路径")
    args = parser.parse_args()
    generate_weekly_report(args.db, args.output)
